package com.jamid.codesquare

const val COLLAB_DB = "collab-db"

const val HOME_PAGE_COUNT = 2
const val PROFILE_PAGE_COUNT = 2
const val MAX_LINES = 4
const val ONE = "1"

const val CREATED_AT = "createdAt"
const val UPDATED_AT = "updatedAt"
const val ID = "id"

const val SENDER = "sender"

const val FILE_PROV_AUTH = "com.jamid.codesquare.fileprovider"
const val PURCHASES = "purchases"

const val POST_TITLE = "postTitle"
const val POST_IMAGE = "postImage"
const val SOURCES = "sources"
const val TAGS = "tags"
const val IMAGES = "images"
const val LOCATION = "location"
const val NAME = "name"

const val image = "Image"
const val text = "Text"
const val document = "Document"

const val COMMENT = "comment"


const val LAST_MESSAGE = "lastMessage"

// Other
const val ARCHIVED = "archived"
const val COMMENT_CHANNEL_ID = "commentChannelId"
const val COMMENT_CHANNELS = "commentChannels"
const val COMMENT_ID = "commentId"
const val CHAT_CHANNELS = "chatChannels"
const val MESSAGE = "message"
const val MESSAGES = "messages"
const val COMMENTS = "comments"
const val COMMENTS_COUNT = "commentsCount"
const val PARENT = "parent"
const val POST_ID = "postId"
const val LIKED_POSTS = "likedPosts"
const val LIKED_COMMENTS = "likedComments"
const val SENDER_ID = "senderId"
const val POST_REQUESTS = "postRequests"
const val REQUESTS = "requests"
const val USER = "user"
const val REPORT = "report"
const val TITLE = "title"
const val SUB_TITLE = "subtitle"
const val POSTS = "posts"
const val CONTRIBUTORS = "contributors"
const val CHAT_CHANNEL = "chatChannel"
const val USERS = "users"
const val LIKES_COUNT = "likesCount"
const val LAST_COMMENT = "lastComment"

const val VIEWS_COUNT = "viewsCount"

const val REPLIES_COUNT = "repliesCount"
const val LIKED_USERS = "likedUsers"
const val NOTIFICATIONS = "notifications"
const val CONTENT = "content"
const val COLLABORATIONS = "collaborations"
const val COLLABORATIONS_COUNT = "collaborationsCount"
const val ADMINISTRATORS = "administrators"
const val CONTRIBUTORS_COUNT = "contributorsCount"
const val TOKENS = "tokens"
const val TOKEN = "token"
const val SAVED_POSTS = "savedPosts"
const val POST = "post"
const val ARCHIVE = "archive"
const val LOCATION_RADIUS = "location_radius"
const val PROFILE_UPDATE = "profile_update"
const val PROFILE_SAVED = "profile_saved"
const val PROFILE_ARCHIVED = "profile_archived"
const val ACCOUNT_UPDATE_PASSWORD = "account_update_password"
const val ACCOUNT_FORGOT_PASSWORD = "account_forgot_password"
const val POSTS_COUNT = "postsCount"
const val CHANNEL_ID = "channelId"
const val POST_INVITES = "postInvites"
const val INVITES = "invites"
const val REPORTS = "reports"
const val INTERESTS = "interests"
const val NOTIFICATION_ID = "notificationId"
const val TYPE = "type"
const val USER_ID = "userId"
const val USERNAME = "username"
const val EXPIRED_AT = "expiredAt"
const val ARCHIVED_POSTS = "archivedPosts"
const val INTERESTS_COLLECTION = "interestsCollection"

const val USER_IMG_1 = "https://firebasestorage.googleapis.com/v0/b/codesqaure.appspot.com/o/images%2Fdefault%2Fa1.jpg?alt=media&token=0c0d875f-e0a2-42a6-891f-716b7b47ba2a"
const val USER_IMG_2 = "https://firebasestorage.googleapis.com/v0/b/codesqaure.appspot.com/o/images%2Fdefault%2Fa2.jpg?alt=media&token=3001b91d-9e1e-465d-8a08-caf9f9ed81fe"
const val USER_IMG_3 = "https://firebasestorage.googleapis.com/v0/b/codesqaure.appspot.com/o/images%2Fdefault%2Fa3.jpg?alt=media&token=898dd6a1-664a-4154-a175-95bb8f1df2ef"
const val USER_IMG_4 = "https://firebasestorage.googleapis.com/v0/b/codesqaure.appspot.com/o/images%2Fdefault%2Fa4.jpg?alt=media&token=409da6dd-197a-45cb-9709-b86a7a0d7fa3"
const val USER_IMG_5 = "https://firebasestorage.googleapis.com/v0/b/codesqaure.appspot.com/o/images%2Fdefault%2Fa5.jpg?alt=media&token=827a0561-a4f6-4482-b589-5b84ea6e4eb9"
const val USER_IMG_6 = "https://firebasestorage.googleapis.com/v0/b/codesqaure.appspot.com/o/images%2Fdefault%2Fa6.jpg?alt=media&token=c5a58dc9-8bb8-41ed-9f9d-c4a4b69238cd"
const val USER_IMG_7 = "https://firebasestorage.googleapis.com/v0/b/codesqaure.appspot.com/o/images%2Fdefault%2Fa7.jpg?alt=media&token=54a70f7f-1d3b-4f56-a5c9-3f42c4f51dec"
const val USER_IMG_8 = "https://firebasestorage.googleapis.com/v0/b/codesqaure.appspot.com/o/images%2Fdefault%2Fa8.jpg?alt=media&token=90013468-bc6c-4867-9dd8-4ecbeea480a0"

val userImages = listOf(USER_IMG_1, USER_IMG_2, USER_IMG_3, USER_IMG_4, USER_IMG_5, USER_IMG_6, USER_IMG_7, USER_IMG_8)

// options
const val OPTION_1 = "Set as admin"
const val OPTION_2 = "Remove from admin"
const val OPTION_3 = "Like "
const val OPTION_4 = "Dislike "
const val OPTION_5 = "Report "
const val OPTION_6 = "Remove from post"
const val OPTION_7 = "Leave post"
const val OPTION_8 = "Select images"
const val OPTION_9 = "Select documents"
const val OPTION_10 = "Save post"
const val OPTION_11 = "Remove from saved"
const val OPTION_12 = "Archive post"
const val OPTION_13 = "Unarchive post"
const val OPTION_14 = "Report"
const val OPTION_15 = "Edit post"
const val OPTION_16 = "View post"
const val OPTION_17 = "Select image"
const val OPTION_18 = "Remove photo"
const val OPTION_19 = "Reply"
const val OPTION_20 = "Forward"
const val OPTION_21 = "Message details"
const val OPTION_22 = "View sender profile"
const val OPTION_23 = "Log out"
const val OPTION_24 = "Saved posts"
const val OPTION_25 = "Archived posts"
const val OPTION_26 = "My requests"
const val OPTION_27 = "Settings"
const val OPTION_28 = "Add to your interests"
const val OPTION_29 = "Report comment"
const val OPTION_30 = "Delete comment"
const val OPTION_31 = "Sent invites"
const val OPTION_32 = "View profile"
const val OPTION_33 = "Block"
const val OPTION_34 = "Unblock"
const val PREVIOUS_POST = "prev_post"

const val HTTPS = "https"

const val FEEDBACKS = "feedbacks"

const val DELIVERY_LIST = "deliveryList"
const val CREATOR = "creator"
const val READ_LIST = "readList"
const val READ = "read"

const val PREF_CREATE_TOOLTIP = "PREF_CREATE_TOOLTIP"
const val PREF_POST_TAGS = "PREF_POST_TAGS"
const val PREF_SCROLL_TOP = "PREF_SCROLL_TOP"
const val PREF_SCROLL_TOP_ALT = "PREF_SCROLL_TOP_ALT"