package com.jamid.codesquare

const val CODESQUARE_DB = "codesquare-db"

const val HOME_PAGE_COUNT = 2
const val PROFILE_PAGE_COUNT = 2
const val MAX_LINES = 4
const val ONE = "1"

const val CREATED_AT = "createdAt"
const val UPDATED_AT = "updatedAt"

const val FILE_PROV_AUTH = "com.jamid.codesquare.fileprovider"
const val PURCHASES = "purchases"

const val PROJECT_TITLE = "projectTitle"
const val PROJECT_IMAGE = "projectImage"
const val SOURCES = "sources"
const val TAGS = "tags"
const val IMAGES = "images"
const val NAME = "name"

const val image = "Image"
const val text = "Text"
const val document = "Document"

// Other
const val ARCHIVED = "archived"
const val COMMENT_CHANNEL_ID = "commentChannelId"
const val COMMENT_CHANNELS = "commentChannels"
const val COMMENT_ID = "commentId"
const val CHAT_CHANNELS = "chatChannels"
const val MESSAGE = "message"
const val MESSAGES = "messages"
const val CHANNELS = "channels"
const val COMMENTS = "comments"
const val PARENT = "parent"
const val PROJECT_ID = "projectId"
const val LIKED_PROJECTS = "likedProjects"
const val SENDER_ID = "senderId"
const val PROJECT_REQUESTS = "projectRequests"
const val REQUESTS = "requests"
const val CONTEXT_OBJECT = "contextObject"
const val USER = "user"
const val TITLE = "title"
const val SUB_TITLE = "subtitle"
const val PROJECTS = "projects"
const val CONTRIBUTORS = "contributors"
const val CHAT_CHANNEL = "chatChannel"
const val USERS = "users"
const val LIKES_COUNT = "likesCount"
const val LIKED_USERS = "likedUsers"
const val NOTIFICATIONS = "notifications"
const val CONTENT = "content"
const val COLLABORATIONS = "collaborations"
const val COLLABORATIONS_COUNT = "collaborationsCount"
const val ADMINISTRATORS = "administrators"
const val CONTRIBUTORS_COUNT = "contributorsCount"
const val REGISTRATION_TOKENS = "registrationTokens"
const val PROJECT = "project"
const val ARCHIVE = "archive"
const val PROJECT_EXPIRY = "project_expiry"
const val LOCATION_RADIUS = "location_radius"
const val PROFILE_UPDATE = "profile_update"
const val PROFILE_SAVED = "profile_saved"
const val PROFILE_ARCHIVED = "profile_archived"
const val ACCOUNT_UPDATE_PASSWORD = "account_update_password"
const val ACCOUNT_FORGOT_PASSWORD = "account_forgot_password"
const val PROJECTS_COUNT = "projectsCount"
const val CHANNEL_ID = "channelId"
const val PROJECT_INVITES = "projectInvites"
const val INVITES = "invites"
const val REPORTS = "reports"
const val NOTIFICATION_ID = "notificationId"
const val TYPE = "type"
const val USER_ID = "userId"

const val USER_IMG_1 = "https://firebasestorage.googleapis.com/v0/b/codesqaure.appspot.com/o/images%2Fdefault%2Fa1.jpg?alt=media&token=0c0d875f-e0a2-42a6-891f-716b7b47ba2a"
const val USER_IMG_2 = "https://firebasestorage.googleapis.com/v0/b/codesqaure.appspot.com/o/images%2Fdefault%2Fa2.jpg?alt=media&token=3001b91d-9e1e-465d-8a08-caf9f9ed81fe"
const val USER_IMG_3 = "https://firebasestorage.googleapis.com/v0/b/codesqaure.appspot.com/o/images%2Fdefault%2Fa3.jpg?alt=media&token=898dd6a1-664a-4154-a175-95bb8f1df2ef"
const val USER_IMG_4 = "https://firebasestorage.googleapis.com/v0/b/codesqaure.appspot.com/o/images%2Fdefault%2Fa4.jpg?alt=media&token=409da6dd-197a-45cb-9709-b86a7a0d7fa3"
const val USER_IMG_5 = "https://firebasestorage.googleapis.com/v0/b/codesqaure.appspot.com/o/images%2Fdefault%2Fa5.jpg?alt=media&token=827a0561-a4f6-4482-b589-5b84ea6e4eb9"
const val USER_IMG_6 = "https://firebasestorage.googleapis.com/v0/b/codesqaure.appspot.com/o/images%2Fdefault%2Fa6.jpg?alt=media&token=c5a58dc9-8bb8-41ed-9f9d-c4a4b69238cd"
const val USER_IMG_7 = "https://firebasestorage.googleapis.com/v0/b/codesqaure.appspot.com/o/images%2Fdefault%2Fa7.jpg?alt=media&token=54a70f7f-1d3b-4f56-a5c9-3f42c4f51dec"
const val USER_IMG_8 = "https://firebasestorage.googleapis.com/v0/b/codesqaure.appspot.com/o/images%2Fdefault%2Fa8.jpg?alt=media&token=90013468-bc6c-4867-9dd8-4ecbeea480a0"
const val USER_IMG_9 = "https://firebasestorage.googleapis.com/v0/b/codesqaure.appspot.com/o/images%2Fdefault%2Fa9.jpg?alt=media&token=18141416-e5f6-463c-b7e1-cd1f37b8d165"
const val USER_IMG_10 = "https://firebasestorage.googleapis.com/v0/b/codesqaure.appspot.com/o/images%2Fdefault%2Fa10.jpg?alt=media&token=f0b22ec2-6b1e-47ac-a9cb-c1eefa2c4d98"
const val USER_IMG_11 = "https://firebasestorage.googleapis.com/v0/b/codesqaure.appspot.com/o/images%2Fdefault%2Fa11.jpg?alt=media&token=3e7ae8cb-b844-4b64-96b3-005c7ea0657f"
const val USER_IMG_12 = "https://firebasestorage.googleapis.com/v0/b/codesqaure.appspot.com/o/images%2Fdefault%2Fa12.jpg?alt=media&token=50b82ee8-5ec2-4c1d-92bd-9b4120b86024"
const val USER_IMG_13 = "https://firebasestorage.googleapis.com/v0/b/codesqaure.appspot.com/o/images%2Fdefault%2Fa13.jpg?alt=media&token=0df4abc9-a085-4b7f-8a0a-49ed14b07754"
const val USER_IMG_14 = "https://firebasestorage.googleapis.com/v0/b/codesqaure.appspot.com/o/images%2Fdefault%2Fa14.jpg?alt=media&token=50beec53-ffdb-4cd7-b279-ef85a429c497"
const val USER_IMG_15 = "https://firebasestorage.googleapis.com/v0/b/codesqaure.appspot.com/o/images%2Fdefault%2Fa15.jpg?alt=media&token=f66c2084-2810-4195-9246-9ab9d1bb3ab0"
const val USER_IMG_16 = "https://firebasestorage.googleapis.com/v0/b/codesqaure.appspot.com/o/images%2Fdefault%2Fa16.jpg?alt=media&token=7d7a3291-56ef-4194-be3c-8aedc221bff9"

val userImages = listOf(USER_IMG_1, USER_IMG_2, USER_IMG_3, USER_IMG_4, USER_IMG_5, USER_IMG_6, USER_IMG_7, USER_IMG_8, USER_IMG_9, USER_IMG_10, USER_IMG_11, USER_IMG_12, USER_IMG_13, USER_IMG_14, USER_IMG_15, USER_IMG_16)

// options
const val OPTION_1 = "Set as admin"
const val OPTION_2 = "Remove from admin"
const val OPTION_3 = "Like "
const val OPTION_4 = "Dislike "
const val OPTION_5 = "Report "
const val OPTION_6 = "Remove from project"
const val OPTION_7 = "Leave project"
const val OPTION_8 = "Select images"
const val OPTION_9 = "Select documents"
const val OPTION_10 = "Save project"
const val OPTION_11 = "Remove from saved"
const val OPTION_12 = "Archive project"
const val OPTION_13 = "Unarchive project"
const val OPTION_14 = "Report"
const val OPTION_15 = "Edit project"
const val OPTION_16 = "View project"
const val OPTION_17 = "Select image"
const val OPTION_18 = "Remove photo"
const val OPTION_19 = "Reply"
const val OPTION_20 = "Forward"
const val OPTION_21 = "Message details"
const val OPTION_22 = "View sender profile"
const val OPTION_23 = "Log out"
const val OPTION_24 = "Saved projects"
const val OPTION_25 = "Archived projects"
const val OPTION_26 = "My requests"
const val OPTION_27 = "Settings"